CREATE TABLE camera
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url     VARCHAR(255),
    label   VARCHAR(255),
    status  VARCHAR(255),
    zone_id BIGINT,
    CONSTRAINT pk_camera PRIMARY KEY (id)
);

CREATE TABLE file
(
    id             UUID NOT NULL,
    bucket         VARCHAR(255),
    name           VARCHAR(255),
    path           VARCHAR(255),
    size           BIGINT,
    file_extension VARCHAR(255),
    status         VARCHAR(255),
    person_id      UUID,
    CONSTRAINT pk_file PRIMARY KEY (id)
);

CREATE TABLE person
(
    id          UUID NOT NULL,
    name        VARCHAR(255),
    middle_name VARCHAR(255),
    surname     VARCHAR(255),
    status      SMALLINT,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE person_in_zone_duration
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id           UUID,
    zone_id             BIGINT,
    duration            BIGINT,
    last_calculate_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_personinzoneduration PRIMARY KEY (id)
);

CREATE TABLE person_last_seen
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id UUID,
    last_seen TIMESTAMP WITHOUT TIME ZONE,
    camera_id BIGINT,
    zone_id   BIGINT,
    CONSTRAINT pk_personlastseen PRIMARY KEY (id)
);

CREATE TABLE zone
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label  VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT pk_zone PRIMARY KEY (id)
);

ALTER TABLE file
    ADD CONSTRAINT uc_file_path UNIQUE (path);

ALTER TABLE camera
    ADD CONSTRAINT FK_CAMERA_ON_ZONE FOREIGN KEY (zone_id) REFERENCES zone (id);

ALTER TABLE file
    ADD CONSTRAINT FK_FILE_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE person_in_zone_duration
    ADD CONSTRAINT FK_PERSONINZONEDURATION_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE person_in_zone_duration
    ADD CONSTRAINT FK_PERSONINZONEDURATION_ON_ZONE FOREIGN KEY (zone_id) REFERENCES zone (id);

ALTER TABLE person_last_seen
    ADD CONSTRAINT FK_PERSONLASTSEEN_ON_CAMERA FOREIGN KEY (camera_id) REFERENCES camera (id);

ALTER TABLE person_last_seen
    ADD CONSTRAINT FK_PERSONLASTSEEN_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE person_last_seen
    ADD CONSTRAINT FK_PERSONLASTSEEN_ON_ZONE FOREIGN KEY (zone_id) REFERENCES zone (id);