server:
  forward-headers-strategy: native
  port: ${SERVER_PORT:8083}
  jetty:
    max-http-response-header-size: 200MB
spring:
  application:
    name: rtsp-server
  servlet:
    multipart:
      max-file-size: 1GB  # Максимально допустимое значение
      max-request-size: 1GB
      enabled: true
  main:
    allow-circular-references: true